### ISSUE TITLE
COBie Lite serializer does not work

### ISSUE THREAD

**Issue by klokoy** [opensourceBIM/COBie-plugins#1]
Im trying to download a revision using the COBie Lite serializer, I do get an actionId but when I try to get the data using getDownloadData I get no response. I have tried using the admin/console with the same result. All other serializers seems to work. Any tip on what the problem might be is very welcomed.

I´m using version 1.2

**Comment by OhmSweetOhm** [comment]
I'm actually surprised that the other COBie plugins work as they have not been updated since a few months before the 1.2 release.  We should have an update soon though.

I'm not sure what the problem could be.  How large is the file?

**Comment by klokoy** [comment]
I´m sorry for expressing myself unclear, but by other I did mean "no COBie plugins". The COBie plugins all failed.  The file is only 2.4 MB.  

Clip from the log: 

```
(org.bimserver.plugins.serializers.SerializerInputstream.java:58) 
org.bimserver.plugins.serializers.SerializerException: java.lang.ClassCastException
    at org.erdc.cobie.utils.serializer.BIMServerCOBieSheetXMLDataSerializer.write(Unknown Source)
    at org.bimserver.plugins.serializers.SerializerInputstream.read(SerializerInputstream.java:41)
    at java.io.InputStream.read(InputStream.java:82)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1025)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:999)
    at org.bimserver.shared.json.JsonConverter.toJson(JsonConverter.java:89)
    at org.bimserver.shared.json.JsonConverter.toJson(JsonConverter.java:68)
    at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:133)
    at org.bimserver.JsonHandler.execute(JsonHandler.java:60)
    at org.bimserver.servlets.JsonApiServlet.handleRequest(JsonApiServlet.java:89)
    at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:71)
    at org.bimserver.servlets.RootServlet.service(RootServlet.java:94)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:457)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:364)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:488)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:943)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1004)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.ClassCastException
15:52:25 INFO  Transforming IFC to COBie.                                                       (org.erdc.cobie.shared.cobiesheetxmldata.COBieFactory.java:?) 
15:52:25 INFO  COBie Serializer: Writing Contact Sheet                                          (org.erdc.cobie.utils.serializer.sheetserializers.IfcPersonOrganizationContactsSerializer.java:?) 
15:52:25 INFO  COBie Serializer: 1 Contacts written, 0 errors.                                  (org.erdc.cobie.utils.serializer.sheetserializers.IfcPersonOrganizationContactsSerializer.java:?) 
15:52:25 INFO  COBie Serializer: Writing Facility Sheet                                         (org.erdc.cobie.utils.serializer.sheetserializers.IfcToFacility.java:?) 
```

**Comment by OhmSweetOhm** [comment]
If you're still in need of the COBie plugin, it has been updated for BIMServer 1.4 and the .jar is available for download.
