### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by zhenchaoli** [opensourceBIM/COBie-plugins#5]
Hi!

I see there are some build.xml files scattered in the project so I assume the project could be built with ant? But when I tried building the project it ran into various problems:

$ ant
Buildfile: c:\Users\mmdb\workspace\COBie-plugins\COBiePlugins_Public\build.xml

build-subprojects:

BUILD FAILED
c:\Users\mmdb\workspace\COBie-plugins\COBiePlugins_Public\build.xml:137: The following error occurred while executing this line:
java.io.FileNotFoundException: c:\Users\mmdb\workspace\COBie-plugins\Emf\build.xml (Cannot find file)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:250)
        at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:178)
        at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:93)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:392)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:853)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

Total time: 0 seconds

Could you tell me how is the project supposed to be built with ant? (We want to add some new features to the project so we don't want to use the prebuilt jar files)

Thanks a lot!

**Comment by OhmSweetOhm** [comment]
Yes, you can use the ant scripts in COBieShared/build to build the plugin jar.

In the current version of the COBiePlugins the classpath is referencing the BIMServerLib files that you can download here...https://github.com/opensourceBIM/BIMserver/releases/download/1.4.0-FINAL-2015-09-12/bimserver-lib-1.4.0-FINAL-2015-09-12.zip

You need to check the .classpath files to make sure that your relative paths are good.

Then I made a NonExportedLib folder in the COBieShared project to cover other dependencies that are included in the BIMServer.jar (and available at runtime) that I did not want to include in the COBiePluin .jar.  

I was doing it this way to avoid having to import the entire BIMServer source code into my workspace as I have done in the past.  However, this has caused other headaches, so in the next revision I'm going back to a .classpath that references the BIMServer Project directories.
